### ISSUE TITLE
Secrets and configs

### ISSUE THREAD

**Issue by danielepolencic** [learnk8s/kubernetes-production-best-practices#5]
“Injected environment variables are always present and may become artifacts in logs for the entire system”
Secret-based environment variables should be sourced from a separate file (volume) in such a way they’re only available to the desired process/container. Not the whole pod.

Source: https://twitter.com/jeyfelbrandauer/status/1194752211366088704

**Comment by weibeld** [comment]
I added the quotes and source to the [TODO](https://github.com/learnk8s/kubernetes-production-best-practices/blob/master/TODO.md).
