### ISSUE TITLE
use kube2iam in favor of disabling metadata endpoints

### ISSUE THREAD

**Issue by dalvizu** [learnk8s/kubernetes-production-best-practices#7]
This checklist: 

> Disable metadata cloud providers metada[sic] API

In AWS, this advice precludes containerized applications from using for example AWS IAM role based authentication, a security best practice: credentials are not hard coded, are automatically rotated, and will likely never leave the cluster itself. For more information on this best practice, read here: https://docs.aws.amazon.com/general/latest/gr/aws-access-keys-best-practices.html#use-roles

As a best practice to use this, I would recommend using kube2iam (https://github.com/jtblin/kube2iam) -- this allows you to control which roles a pod is allowed to assume based on namespace, but also allows the pod to see itself as having the role vs requiring it to assume such a role.

In our setup we use kube2iam and assign nodes their IAM role - this IAM role is allowed to assume other roles. With kube2iam, we assign the role through a pod annotation, so the pod sees itself as having that role. Additionally we use namespace restrictions to control access to which roles a pod is allowed to assume.

**Comment by weibeld** [comment]
Hi @dalvizu, thanks for the comment. We will note this for the next iteration of the checklist. We're planning to expand the checklist to include cloud provider specific items, so we will probably include kube2iam as a best practice for AWS.

**Comment by weibeld** [comment]
Just noted in the [TODO](https://github.com/learnk8s/kubernetes-production-best-practices/blob/master/TODO.md#amazon-web-services-aws)

**Comment by weibeld** [comment]
Closing, as this has bee noted.
